server.port=8081
spring.application.name=final-exam-lost
spring.datasource.url=jdbc:mysql://localhost:3306/final_web_exam?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.cache=false
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
student.name=\u5362\u6797\u9487
student.no=24053010204
debug=true


